### ISSUE TITLE
Tuan's issues

### ISSUE THREAD

**Issue by phuongngo0320** [N3Mobile/finwise#37]
có vài vấn đề nè mng:
- trang lịch sử khi bấm vào nên tự reload lại (hiện tại phải bấm tìm kiếm nó mới gọi api lại)
- thêm giao dịch thì nên reset lại hết (hiện tại thêm giao dịch lại nó vẫn lưu thông tin của giao dịch trước)
- trang lịch sử t test thì hiển thị được có 4 cái @@ có trượt nhma k đáng kể... k trượt tới được cái thứ 5

**Comment by HpT2** [comment]
Fixed history screen bug
